# Generated by Django 4.1.7 on 2023-03-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crudpro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogname', models.CharField(max_length=150)),
                ('blogdes', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
